name: Initialize
on:
  workflow_dispatch:
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Check package.json
        run: |
          if [ ! -f package.json ]; then
            echo "package.json not found.\n\tInitializing..."
            npm init -y
          else
            echo "package.json found.\n\tContinuing..."
          fi
      - name: Check package-lock.json
        run: |
          if [ ! -f package-lock.json ]; then
            echo "package-lock.json not found.\n\tInitializing..."
            npm install
          else
            echo "package-lock.json found.\n\tContinuing..."
          fi
      - name: Configure Git
        run: |
          git config --global user.name "github-gremlin"
          git config --global user.email "github-gremlin@users.noreply.github.com"
      - name: Commit changes
        run: |
          git add .
          git commit -m "Auto-commit: update from script" || echo "No changes to commit"
          git push
